name: Calling workflow

on:
  workflow_dispatch:

jobs:
  call_workflow:
    uses: ./github/workflows/reusable-workflow.yml
    with:
      who-to-greet: Yogini

  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
    
    
